---
hero_image: images/live-dj.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Live DJ
description: Leer hoe je een live muziekoptreden codeert.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/live-dj
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017/01/01
steps:
- title: Inleiding
  completion: engaged
- title: Drums
- title: 'Uitdaging: de drum loop wijzigen'
- title: Een sample toevoegen
- title: 'Uitdaging: de sample veranderen'
- title: Bas toevoegen
- title: 'Uitdaging: de bas veranderen'
- title: Geluidseffecten toevoegen
- title: 'Uitdaging: de effecten veranderen'
  completion: internal
- title: 'Uitdaging: Pronk met je DJ-vaardigheden!'
