---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Live DJ
description: Learn how to code a live music performance.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/live-dj
interests: music/sound
technologies: ''
site_areas: codeclub, sonic-pi
steps:
- title: Drums
- title: 'Challenge: Changing the drum loop'
- title: Adding a sample
- title: 'Challenge: Changing the sample'
- title: Adding bass
- title: 'Challenge: Changing the bass'
- title: Adding sound effects
- title: 'Challenge: Changing the effects'
- title: 'Challenge: Show off your DJ skills!'

