---
hero_image: images/live-dj.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Live-DJ
description: Lernen Sie, wie Sie eine Live-Musik-Performance codieren.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/live-dj
interests: musik
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Schlagzeug
  - 
    title: 'Herausforderung: Drumloop wechseln'
  - 
    title: Probe hinzufügen
  - 
    title: 'Herausforderung: Probe wechseln'
  - 
    title: Bass hinzufügen
  - 
    title: 'Herausforderung: Bass wechseln'
  - 
    title: Soundeffekte hinzufügen
  - 
    title: 'Herausforderung: Ändern der Effekte'
  - 
    title: 'Herausforderung: Zeigen Sie Ihre DJ-Fähigkeiten!'
