---
hero_image: images / live-dj.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-0, comunitat-0
title: Live DJ
description: Learn how to code a live music performance.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/live-dj
interests: música
technologies: ''
site_areas: projectes
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Drums
  - 
    title: 'Challenge: Changing the drum loop'
  - 
    title: Adding a sample
  - 
    title: 'Challenge: Changing the sample'
  - 
    title: Adding bass
  - 
    title: 'Challenge: Changing the bass'
  - 
    title: Adding sound effects
  - 
    title: 'Challenge: Changing the effects'
  - 
    title: 'Challenge: Show off your DJ skills!'
