---
hero_image: images/live-dj.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: DJ en vivo
description: Aprende a programar un espectáculo musical en vivo.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/live-dj
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: Batería
- title: 'Desafío: Cambia la secuencia de la batería'
- title: Añade una muestra
- title: 'Desafío: Cambia la muestra'
- title: Añade un bajo
- title: 'Desafío: Cambia el bajo'
- title: Añade efectos de sonido
- title: 'Desafío: Cambia los efectos de sonido'
  completion: internal
- title: 'Desafío: ¡Demuestra tus habilidades de DJ!'
