---
hero_image: images/live-dj.png
theme: bleu
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Live DJ
description: Learn how to code a live music performance.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/live-dj
interests: musique
technologies: ''
site_areas: projets
hardware: ''
software: ''
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introduction
  - 
    title: Drums
  - 
    title: 'Challenge: Changing the drum loop'
  - 
    title: Adding a sample
  - 
    title: 'Challenge: Changing the sample'
  - 
    title: Adding bass
  - 
    title: 'Challenge: Changing the bass'
  - 
    title: Adding sound effects
  - 
    title: 'Challenge: Changing the effects'
  - 
    title: 'Challenge: Show off your DJ skills!'
